# Default values for zipkin.
collector:
  replicaCount: 4
  maxReplicaCount: 4
  targetCPUUtilizationPercentage: 80
  imageVersion: 1.28.1
  sampleRate: 0.0000001
  probeStartupDelay: 150
  queryPort: 9411
  resources:
    ramMb: 700
    javaOptsHeap: 900
    cpuRequest: 150m
    cpuLimit: 200m

ui:
  replicaCount: 1
  imageVersion: 1.28.1
  probeStartupDelay: 150
  queryPort: 9411
  resources:
    ramMb: 700
    javaOptsHeap: 900
    cpuRequest: 150m
    cpuLimit: 200m

dependencies:
  enabled: true
  cron: "0 22 * * *"
  imageVersion: 1.6.1
  resources:
    ramMb: 700
    javaOptsHeap: 900
    cpuRequest: 150m
    cpuLimit: 200m

configmap:
  name: zipkin
  contactPoints:
    name: zipkin
    key: cassandra.contactpoints
  username:
    name: zipkin
    key: cassandra.username
  localdc:
    name: zipkin
    key: cassandra.localdc

ingress:
  class: "istio"
  host: placeholder
  path: /.*
  serviceName: zipkin-ui
  servicePort: 9411

storageMethod: cassandra

cassandra:
  username: placeholder
  password: placeholder
  contactPoints: placeholder
  localdc: placeholder
  ensureSchema: false

node:
  cpus: 2


